from copy import deepcopy
from dataclasses import InitVar, dataclass, field
from math import inf
from typing import List, Optional

from RUFAS.general_constants import GeneralConstants
from RUFAS.output_manager import OutputManager
from RUFAS.biophysical.field.soil.layer_data import LayerData
from RUFAS.biophysical.field.soil.manure_pool import ManurePool


@dataclass(kw_only=True)
class SoilData:
    """
    This is a data class that stores and tracks all Soil attributes that are given in input files as well as ones that
    are generated by modules in Soil.

    Attributes
    ----------
    name : string, optional, default "generic soil configuration"
        Name of the soil configuration.
    soil_layers : List[LayerData], optional, default None
        List of soil layer data objects, where the top layer is the 0th element and the bottom is the nth element.
    field_size : InitVar[float], default None
        Size of the field (ha).
        Note: this attribute is only used for initialization. After that, it cannot be used.
    initial_water_content : float, default None
        Total soil water content at the beginning of a year, for use in determining annual change (mm).
    initial_nitrates_total : float, default None
        Total soil nitrate amounts at the beginning of a year, for use in determining annual change (kg per hectare).
    annual_soil_evaporation_total : float, default 0
        Cumulative total of water evaporated from the soil this year (mm).
    annual_runoff_total : float, default 0
        Cumulative total of runoff that occurred in a year (mm).
    annual_eroded_sediment_total : float, default 0
        Cumulative total of sediment that eroded in a year (metric tons).
    annual_surface_runoff_total : float, default 0
        Cumulative total of the volume of surface runoff that occurred in a year (mm per hectare).
    annual_runoff_fertilizer_phosphorus : float, default 0
        Cumulative total of phosphorus from surface-applied fertilizer that was carried off the field by runoff (kg).
    annual_runoff_machine_manure_inorganic_phosphorus : float, default 0
        Cumulative total of inorganic phosphorus from machine-applied manure that was carried off the field by runoff
        (kg).
    annual_runoff_machine_manure_organic_phosphorus : float, default 0
        Cumulative total of organic phosphorus from machine-applied manure that was carried off the field by runoff
        (kg).
    annual_runoff_grazing_manure_inorganic_phosphorus : float, default 0
        Cumulative total of inorganic phosphorus from grazer-applied manure that was carried off the field by runoff
        (kg).
    annual_runoff_grazing_manure_organic_phosphorus : float, default 0
        Cumulative total of organic phosphorus from grazer-applied manure that was carried off the field by runoff (kg).
    annual_soil_phosphorus_runoff : float, default 0
        Cumulative total of phosphorus that was from the top layer of the soil profile by runoff (kg / ha).
    annual_runoff_nitrates_total : float, default 0
        Cumulative total of nitrates that were removed from the top soil layer by runoff (kg).
    annual_runoff_ammonium_total : float, default 0
        Cumulative total of ammonium that was removed from the top soil layer by runoff (kg).
    annual_eroded_fresh_organic_nitrogen_total : float, default 0
        Cumulative total of fresh organic nitrogen that was removed from the top soil layer by erosion (kg).
    annual_eroded_stable_organic_nitrogen_total : float, default 0
        Cumulative total of stable organic nitrogen that was removed from the top soil layer by erosion (kg).
    annual_eroded_active_organic_nitrogen_total : float, default 0
        Cumulative total of active organic nitrogen that was removed from the top soil layer by erosion (kg).
    water_evaporated : float, default 0.0
        Amount of water evaporated from the soil profile on the current day (mm).
    second_moisture_condition_parameter : float, default 85
        'Curve number' parameter for average moisture conditions equation (unitless).
    previous_retention_parameter : Optional[float], default None
        Retention parameter for the previous day (mm) (used in SWAT 2:1.1.9).
    average_subbasin_slope : float, default 0.05
        Average slope of the subbasin expressed as rise over run (meters/meters).
    moisture_condition_parameter : Optional[float], default None
        Curve number value adjusted for moisture content (unitless) (SWAT 2:1.1.11).
    accumulated_runoff : float, default 0.0
        Amount of rainfall discharged as runoff on the current day (mm).
    infiltrated_water : float, default 0.0
        Amount of water that infiltrated the soil profile on the day (mm).
    vadose_zone_layer : Optional[LayerData], default None
        LayerData object that represents the vadose zone layer, where the top depth is set equal to the bottom depth of
        the lowest soil layer and the bottom depth is arbitrary, starting with no water.
    time_step : float, default 24
        Length of the time step over which percolation occurs (hours).
    albedo : float, default 0.16
        Proportion of solar radiation that is reflected by the soil surface (unitless).
    previous_temperature_effect : float, default 0.8
        Variable that controls the influence of the previous day's temperature on the current day's temperature, ranging
        from 0 to 1, inclusive. SWAT sets the lag coefficient to 0.8 (unitless).
    snow_content : float, default 0.0
        Water content of the snow pack (mm H2O).
    snow_melt_amount : float, default 0.0
        Water content of the snow that melted on the current day (mm H2O).
    previous_day_snow_temperature : Optional[float], default None
        Snow pack temperature on the previous day (ºC).
    current_day_snow_temperature : Optional[float], default None
        Snow pack temperature of the current day (ºC).
    snow_lag_factor : float, default 1.0
        Snow pack temperature lag factor (unitless).
    snow_coverage_fraction : float, default 1.0
        Fraction of snow coverage (unitless).
    snow_melt_base_temperature : float, default 0.5
        Snow melt base temperature (ºC). The snow pack will not melt until the snow pack temperature exceeds this
        threshold value.
    snow_coverage_maximum : float, default 1.0
        Minimum snow water content that corresponds to 100% snow cover (mm H2O).
    snow_melt_factor_maximum : float, default 4.5
        Melt factor for snow on June 21, SMFMX (mm H2O/°C-day).
    snow_melt_factor_minimum : float, default 4.5
        Melt factor for snow on December 21, SMFMN (mm H2O/°C-day).
    water_sublimated : float, default 0.0
        Amount of snow water content lost through sublimation on the current day (mm).
    slope_length : float, default 3
        Length of the slope (meters).
    manning : float, default 0.4
        Manning roughness coefficient for this subbasin (unitless).
    eroded_sediment : float, default 0
        Cumulative amount of sediment that has been eroded off of the field in a day (metric tons).
    surface_runoff_volume : float, optional, default None
        Volume of surface runoff (mm per hectare), used in SWAT equation 4:1.1.1.
    cover_type : str, default "BARE"
        The cover type of the soil surface, which can be bare, residue covered, or grassed.
    full_available_phosphorus_pool : float, default 0
        Starting value of the available phosphorus pool (kg). This value does not change when phosphorus is removed from
        the available phosphorus pool, but does change when a new application of fertilizer phosphorus is applied.
    available_phosphorus_pool : float, default 0
        Amount of phosphorus available for soil adsorption and leaching via runoff before the first rainfall event after
        application (kg).
    recalcitrant_phosphorus_pool : float, default 0
        Amount of phosphorus available for soil adsorption and leaching via runoff after the first rainfall event (kg).
    runoff_fertilizer_phosphorus : float, default 0.0
        Amount of solubilized phosphorus that has been leached off the field by runoff (kg).
    days_since_application : int, default 0
        Number of days since phosphorus was applied to the field via fertilizer.
    rain_events_after_fertilizer_application : int, default 0
        Number of rain events that have occurred since phosphorus was applied to the field via fertilizer.
    soil_phosphorus_runoff : float, default 0.0
        Amount of phosphorus removed from the surface soil layer by runoff (kg / ha).
    nitrate_runoff : float, default 0.0
        Amount of nitrate removed from the soil surface by runoff (kg / ha).
    ammonium_runoff : float, default 0.0
        Amount of ammonium removed from the soil surface by runoff (kg / ha).
    eroded_fresh_organic_nitrogen : float, default 0.0
        Amount of fresh organic nitrogen removed from the soil surface by eroded sediment (kg / ha).
    eroded_stable_organic_nitrogen : float, default 0.0
        Amount of stable organic nitrogen removed from the soil surface by eroded sediment (kg / ha).
    eroded_active_organic_nitrogen : float, default 0.0
        Amount of active organic nitrogen removed from the soil surface by eroded sediment (kg / ha).
    humus_mineralization_rate_factor : float, default 0.0003
        Rate factor for humus mineralization of active organic nutrients (nitrogen and phosphorus) (unitless).
        Reference: SWAT Input .BSN file, see "CMN" on page 101.
    denitrification_rate_coefficient : float, default 1.4
        Controls the rate of denitrification in this layer of soil (unitless).
        Note: acceptable values for this attribute are in the range [0.0, 3.0].
        Reference: SWAT Input .BSN file, see "CDN" on page 101.
    denitrification_threshold_water_content : float, default 1.10
        Fraction of field capacity water content above which denitrification takes place (unitless).
        Reference: SWAT Input .BSN file, see "SDNCO" on page 102.
    residue_fresh_organic_mineralization_rate : float, default 0.05
        Rate coefficient for mineralization of residue fresh organic nutrients (nitrogen and phosphorus) (unitless).
        Reference: SWAT Input .BSN file (see "RSDCO" on page 101) and SWAT Input CROP.DAT file (see "RSDCO_PL" on page
        205).
    plant_residue_lignin_composition : float, default 0.17
        Lignin fraction of plant residue (unitless).
    plant_lignin_nitrogen_ratio : float, default 0
        Plant lignin to nitrogen ratio (unitless).
    plant_residue_metabolic_fraction : float, default 0
        Plant residue fraction that is metabolic (unitless).
    crop_yield_nitrogen : float, default 0
        Nitrogen contained in the harvested yield (kg/ha).
    machine_manure : ManurePool
        A ManurePool instance holding data for machine-applied manure.
    grazing_manure : ManurePool
        A ManurePool instance holding data for grazing-applied manure
    """

    # ID variables
    name: Optional[str] = "generic soil configuration"

    soil_layers: Optional[List[LayerData]] = None
    field_size: InitVar[float] = None

    # Track annual soil profile totals
    initial_water_content: float = None
    initial_nitrates_total: float = None

    # Track annual hydrological activity
    annual_soil_evaporation_total: float = 0
    annual_runoff_total: float = 0

    # Track annual erosion activity
    annual_eroded_sediment_total: float = 0
    annual_surface_runoff_total: float = 0

    # Track annual phosphorus activity
    annual_runoff_fertilizer_phosphorus: float = 0
    annual_soil_phosphorus_runoff: float = 0

    # Track annual nitrogen loss from field
    annual_runoff_nitrates_total: float = 0
    annual_runoff_ammonium_total: float = 0
    annual_eroded_fresh_organic_nitrogen_total: float = 0
    annual_eroded_stable_organic_nitrogen_total: float = 0
    annual_eroded_active_organic_nitrogen_total: float = 0

    # ---- evaporation
    water_evaporated: float = 0.0

    # ---- infiltration
    second_moisture_condition_parameter: float = 85
    previous_retention_parameter: Optional[float] = None
    average_subbasin_slope: float = 0.05
    moisture_condition_parameter: Optional[float] = None
    accumulated_runoff: float = 0.0
    infiltrated_water: float = 0.0

    # ---- percolation
    vadose_zone_layer: Optional[LayerData] = None
    time_step: float = 24

    # ---- temperature
    albedo: float = 0.16
    previous_temperature_effect: float = 0.8

    # ---- Snow
    snow_content: float = 0.0
    snow_melt_amount: float = 0.0
    previous_day_snow_temperature: Optional[float] = None
    current_day_snow_temperature: Optional[float] = None
    snow_lag_factor: float = 1.0
    snow_coverage_fraction: float = 1.0
    snow_melt_base_temperature: float = 0.5
    snow_coverage_maximum: float = 1.0
    snow_melt_factor_maximum: float = 4.5
    snow_melt_factor_minimum: float = 4.5
    water_sublimated: float = 0.0

    # ---- Erosion
    slope_length: float = 3
    manning: float = 0.4
    eroded_sediment: float = 0
    surface_runoff_volume: Optional[float] = None

    # ---- Fertilizer (Phosphorus Cycling)
    cover_type: str = "BARE"
    full_available_phosphorus_pool: float = 0
    available_phosphorus_pool: float = 0
    recalcitrant_phosphorus_pool: float = 0
    runoff_fertilizer_phosphorus: float = 0.0
    days_since_application: int = 0
    rain_events_after_fertilizer_application: int = 0

    # ---- Manure pools (Phosphorus Cycling)
    machine_manure: ManurePool = field(default_factory=ManurePool)
    grazing_manure: ManurePool = field(default_factory=ManurePool)

    soil_phosphorus_runoff: float = 0.0

    # ---- Surface Nitrogen ----
    nitrate_runoff: float = 0.0
    ammonium_runoff: float = 0.0
    eroded_fresh_organic_nitrogen: float = 0.0
    eroded_stable_organic_nitrogen: float = 0.0
    eroded_active_organic_nitrogen: float = 0.0
    humus_mineralization_rate_factor: float = 0.0003
    denitrification_rate_coefficient: float = 1.4
    denitrification_threshold_water_content: float = 1.10
    residue_fresh_organic_mineralization_rate: float = 0.05

    # ---- Residue partition (Carbon Cycling)
    plant_residue_lignin_composition: float = 0.17
    plant_lignin_nitrogen_ratio: float = 0
    plant_residue_metabolic_fraction: float = 0
    crop_yield_nitrogen: float = 0

    @property
    def total_residue(self) -> float:
        """
        Amount of total plant residue, above and below-ground, on the field which is to be transferred to litter pools
        in the soil profile (kg/ha).
        """
        return sum(self.get_vectorized_layer_attribute("plant_residue"))

    def __post_init__(self, field_size: float):
        """
        This method initializes attributes that either cannot be set to a default above or depend on other
        attributes in the object to be set before they can be set.

        Parameters
        ----------
        field_size: float
            Size of the field (ha).

        Raises
        ------
        TypeError
            If the field size is None (meaning it likely was not included when the SoilData() object was initialized).
        ValueError
            If the field size specified is not greater than 0.
            If the bottom depth of the top layer of soil is < 20.

        Notes
        -----
        The SoilData class itself does not need the field size, but it requires it if the soil layers are not defined
        for it.

        """
        if field_size is None:
            raise TypeError("'field_size' attribute is NoneType, must be given value when SoilData is initialized.")
        elif field_size <= 0:
            raise ValueError(f"Expected field_size to be greater than 0, received {field_size}.")

        if self.soil_layers is None:
            self.soil_layers = [
                LayerData(
                    top_depth=0,
                    bottom_depth=20,
                    field_size=field_size,
                    residue=0.0,
                ),
                LayerData(top_depth=20, bottom_depth=50, field_size=field_size),
                LayerData(top_depth=50, bottom_depth=80, field_size=field_size),
                LayerData(top_depth=80, bottom_depth=200, field_size=field_size),
            ]
        elif self.soil_layers[0].bottom_depth < 20:
            raise ValueError(
                f"Expected bottom depth of top soil layer must be 20 mm or greater, received "
                f"'{self.soil_layers[0].bottom_depth}'."
            )
        elif self.soil_layers[0].bottom_depth > 20:
            self._subdivide_top_layer(field_size)

        if self.vadose_zone_layer is None:
            # configures the vadose zone LayerData object based on where the soil profile ends
            self.vadose_zone_layer = LayerData(
                top_depth=self.soil_layers[-1].bottom_depth,
                bottom_depth=10000000,  # bottom depth is 10,000 meters by default
                soil_water_concentration=0,
                saturation_point_water_concentration=inf,
                initial_labile_inorganic_phosphorus_concentration=0,
                initial_soil_nitrate_concentration=0,
                field_size=field_size,
            )
            self.vadose_zone_layer.active_organic_nitrogen_content = 0
            self.vadose_zone_layer.stable_organic_nitrogen_content = 0

        # Set the initial water content for the first year of the simulation
        self.initial_water_content = self.profile_soil_water_content
        self.initial_nitrates_total = self.profile_nitrates_total

        if self.soil_layers[0].silt_fraction == 0 and self.soil_layers[0].clay_fraction == 0:
            om = OutputManager()
            info_map = {
                "class": self.__class__.__name__,
                "function": self.__post_init__.__name__,
            }
            om.add_warning(
                "Silt and clay fractions in the soil are 0, which will lead to unreliable predictions of erosion"
                " and soil emissions",
                "It is assumed that the ratio of clay to silt in the soil layer will not have any effect on the "
                "amount of erosion from the soil.",
                info_map,
            )

    def _subdivide_top_layer(self, field_size: float) -> None:
        """
        This method ensures that the soil profile has a top layer that is 20 mm deep.

        Parameters
        ----------
        field_size : float
            Size of the field (ha).

        Notes
        -----
        The presence of a top layer of soil that is 20 mm deep is a necessity to properly execute SurPhos. This top 20
        mm of soil is where most of the phosphorus that is applied stays in the soil profile, and keeping it in the top
        20 mm of soil makes it more available to be eroded off the field by runoff.

        This method assumes that the top layer of soil defined by the user is greater than 20 mm thick.

        """
        new_top_layer = deepcopy(self.soil_layers[0])
        new_top_layer.bottom_depth = 20
        new_top_layer.__post_init__(field_size, 0.0)
        self.soil_layers[0].top_depth = 20
        self.soil_layers[0].__post_init__(field_size, 0)
        self.soil_layers.insert(0, new_top_layer)

    def get_vectorized_layer_attribute(self, attribute: str) -> List[any]:
        """
        Returns a list containing the specified attribute for each soil layer.

        Parameters
        ----------
        attribute : str
            The LayerData attribute or property to be vectorized.

        Returns
        -------
        layered_attribute : list[any]
            Values of the specified attribute for each layer.

        """
        return [getattr(layer, attribute) for layer in self.soil_layers]

    def set_vectorized_layer_attribute(self, attribute: str, values: List[any]) -> None:
        """
        Sets a given attribute for all layers in soil_data.

        Parameters
        ----------
        attribute : str
            The LayerData attribute to set.
        values : list[any]
            Values of the attribute to set for each layer.

        """
        [setattr(layer, attribute, val) for layer, val in zip(self.soil_layers, values)]

    def do_annual_reset(self) -> None:
        """This method resets all annual totals to zero at the end of the year/beginning of a new year"""
        # Reset soil profile totals
        self.initial_water_content = self.profile_soil_water_content
        self.initial_nitrates_total = self.profile_nitrates_total

        # Reset hydrological activity totals
        self.annual_soil_evaporation_total = 0
        self.annual_runoff_total = 0

        # Reset erosion activity totals
        self.annual_eroded_sediment_total = 0
        self.annual_surface_runoff_total = 0

        # Reset phosphorus totals
        self.annual_runoff_fertilizer_phosphorus = 0
        self.grazing_manure.annual_runoff_manure_inorganic_phosphorus = 0
        self.grazing_manure.annual_runoff_manure_organic_phosphorus = 0
        self.machine_manure.annual_runoff_manure_inorganic_phosphorus = 0
        self.machine_manure.annual_runoff_manure_organic_phosphorus = 0
        self.annual_soil_phosphorus_runoff = 0
        self.machine_manure.annual_decomposed_manure = 0
        self.grazing_manure.annual_decomposed_manure = 0

        self.annual_runoff_nitrates_total = 0
        self.annual_runoff_ammonium_total = 0
        self.annual_eroded_fresh_organic_nitrogen_total = 0
        self.annual_eroded_stable_organic_nitrogen_total = 0
        self.annual_eroded_active_organic_nitrogen_total = 0

        # Reset carbon cycle
        for layer in self.soil_layers:
            layer.do_annual_reset()

    @property
    def profile_soil_water_content(self) -> float:
        """
        Calculate the amount of water in the entire soil profile (excluding the amount of water held in the profile at
        the wilting point) (mm).

        Returns
        -------
        float
            The total soil water content in millimeters (mm).

        Notes
        -----
        This method calculates the total soil water content in the entire soil profile. It assumes that the lower bound
        of water is 0. The calculation is done per layer, meaning that if one layer has water content greater than its
        wilting water point and another layer has water content less than its wilting point, the first layer will not
        have to compensate for the deficit in the second layer.

        """
        water_sum = 0
        for layer in self.soil_layers:
            water_sum += max(0.0, (layer.water_content - layer.wilting_point_content))
        return water_sum

    @property
    def profile_saturation(self) -> float:
        """
        Calculate the amount of water in the soil profile when completely saturated (mm).

        Returns
        -------
        float
            The saturated soil water content in millimeters (mm).

        """
        saturation_sum = 0
        for layer in self.soil_layers:
            saturation_sum += layer.saturation_content
        return saturation_sum

    @property
    def profile_field_capacity(self) -> float:
        """
        Calculate the total amount of water contained in the entire soil profile at field capacity
        (but not saturated) (mm).

        Returns
        -------
        float
            The soil water content at field capacity in millimeters (mm).

        """
        field_capacity_sum = 0
        for layer in self.soil_layers:
            field_capacity_sum += layer.field_capacity_content
        return field_capacity_sum

    @property
    def soil_water_factor(self) -> float:
        """
        Get the soil water factor (unitless).

        Returns
        -------
        float
            The soil water factor, in the range [0.0, 1.0] (unitless).

        References
        ----------
        SWAT Theoretical documentation eqn. 5:2.3.18

        """
        unclamped_water_factor = self.profile_soil_water_content / (0.85 * self.profile_field_capacity)
        clamped_water_factor = min(1.0, max(0.0, unclamped_water_factor))
        return clamped_water_factor

    @property
    def profile_bulk_density(self) -> float:
        """
        Calculate the average bulk density of the soil profile based on the bulk density of each soil layer,
        weighted by the thickness.

        Returns
        -------
        float
            The average bulk density of the soil profile (Mg per cubic meter).

        """
        weighted_densities_sum = 0
        weights_sum = 0
        for layer in self.soil_layers:
            weighted_densities_sum += layer.layer_thickness * layer.bulk_density
            weights_sum += layer.layer_thickness
        return weighted_densities_sum / weights_sum

    @property
    def profile_nitrates_total(self) -> float:
        """
        Calculate and return the total amount of nitrates in the soil.

        Returns
        -------
        float
            The total amount of nitrates in the soil (kg per hectare).

        """
        return sum(self.get_vectorized_layer_attribute("nitrate_content"))

    @property
    def profile_ammonium_total(self) -> float:
        """
        Calculate and return the total amount of nitrates in the soil.

        Returns
        -------
        float
            The total amount of ammonium in the soil (kg / ha).

        """
        return sum(self.get_vectorized_layer_attribute("ammonium_content"))

    @property
    def profile_active_organic_nitrogen_total(self) -> float:
        """
        Calculate and return the total amount of active organic nitrogen in the soil.

        Returns
        -------
        float
            The total amount of active organic nitrogen in the soil (kg / ha).

        """
        return sum(self.get_vectorized_layer_attribute("active_organic_nitrogen_content"))

    @property
    def profile_stable_organic_nitrogen_total(self) -> float:
        """
        Calculate and return the total amount of stable organic nitrogen in the soil.

        Returns
        -------
        float
            The total amount of stable organic nitrogen in the soil (kg / ha).

        """
        return sum(self.get_vectorized_layer_attribute("stable_organic_nitrogen_content"))

    @property
    def profile_fresh_organic_nitrogen_total(self) -> float:
        """
        Calculate and return the total amount of fresh organic nitrogen in the soil.

        Returns
        -------
        float
            The total amount of fresh organic nitrogen in the soil (kg / ha).

        """
        return sum(self.get_vectorized_layer_attribute("fresh_organic_nitrogen_content"))

    @property
    def cover_factor(self) -> float:
        """
        Returns the cover factor based on the cover type for determining phosphorus absorption by soil
        from surface-applied fertilizer before the first rainfall event after application.

        Returns
        -------
        float
            The cover factor (unitless).

        Raises
        ------
        ValueError
            If the cover type is not one of the acceptable types ("BARE", "RESIDUE_COVER", or "GRASSED").

        References
        ----------
        pseudocode_soil [S.5.C.I.1], SurPhos [14] (Note: constants may differ between documents; defer to
        pseudocode_soil and old code).

        """
        if self.cover_type == "BARE":
            return 0.5333
        elif self.cover_type == "RESIDUE_COVER":
            return 0.6667
        elif self.cover_type == "GRASSED":
            return 0.8
        raise ValueError(
            f"Expected cover type to be 'BARE', 'RESIDUE_COVER', or 'GRASSED', " f"received: '{self.cover_type}'."
        )

    @property
    def solubilizing_factor(self) -> float:
        """
        Returns the fraction of fertilizer phosphorus removed from the available or recalcitrant pool based on the
        number of rain events.

        Parameters
        ----------
        rain_events : int
            The number of rain events.

        Returns
        -------
        float
            The fraction of fertilizer phosphorus removed (unitless).

        References
        ----------
        SurPhos paragraph just below [16].

        """
        if self.rain_events_after_fertilizer_application <= 1:
            return 1
        elif self.rain_events_after_fertilizer_application == 2:
            return 0.40
        else:
            return 0.075

    @property
    def profile_carbon_total(self) -> float:
        carbon_pools = [
            "metabolic_litter_amount",
            "structural_litter_amount",
            "active_carbon_amount",
            "slow_carbon_amount",
            "passive_carbon_amount",
        ]
        carbon_total = 0.0
        for pool in carbon_pools:
            carbon_total += sum(self.get_vectorized_layer_attribute(pool))
        return carbon_total

    @property
    def profile_carbon_emissions(self) -> float:
        """
        Calculates the total amount of CO2 respirated from the soil profile.

        Returns
        -------
        float
            Total amount of CO2 emitted from carbon decomposition in the soil profile (kg/ha).

        """
        emissions_from_active = sum(self.get_vectorized_layer_attribute("active_carbon_to_slow_loss"))
        emissions_from_slow = sum(self.get_vectorized_layer_attribute("slow_carbon_co2_lost_amount"))
        emissions_from_passive = sum(self.get_vectorized_layer_attribute("passive_carbon_co2_lost_amount"))
        return emissions_from_active + emissions_from_slow + emissions_from_passive

    @property
    def average_clay_percent(self) -> float:
        """
        Calculates the average percent of soil.

        Returns
        -------
        float
            Average clay percent of the soil (unitless).

        """
        clay_fractions = self.get_vectorized_layer_attribute("clay_fraction")
        clay_percentages = [clay_fraction * GeneralConstants.FRACTION_TO_PERCENTAGE for clay_fraction in clay_fractions]

        return sum(clay_percentages) / len(clay_percentages)
