name: Build Sphinx

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build HTML from Sphinx
      run: |
        sphinx-apidoc -ed 1 --remove-old -o docs/_src/_code/ . ./tests/
        cd docs
        make clean
        make html
    - name: Commit & Push changes to Sphinx Documentation
      uses: actions-js/push@master
      with:
        message: Update Sphinx Documentation
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref_name }}
